# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/TronAddressGen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/TronAddressGen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/TronAddressGen/CMakeFiles /root/TronAddressGen//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/TronAddressGen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TronAddressGen

# Build rule for target.
TronAddressGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TronAddressGen
.PHONY : TronAddressGen

# fast build rule for target.
TronAddressGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/build
.PHONY : TronAddressGen/fast

Dispatcher.o: Dispatcher.cpp.o
.PHONY : Dispatcher.o

# target to build an object file
Dispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/Dispatcher.cpp.o
.PHONY : Dispatcher.cpp.o

Dispatcher.i: Dispatcher.cpp.i
.PHONY : Dispatcher.i

# target to preprocess a source file
Dispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/Dispatcher.cpp.i
.PHONY : Dispatcher.cpp.i

Dispatcher.s: Dispatcher.cpp.s
.PHONY : Dispatcher.s

# target to generate assembly for a file
Dispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/Dispatcher.cpp.s
.PHONY : Dispatcher.cpp.s

Mode.o: Mode.cpp.o
.PHONY : Mode.o

# target to build an object file
Mode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/Mode.cpp.o
.PHONY : Mode.cpp.o

Mode.i: Mode.cpp.i
.PHONY : Mode.i

# target to preprocess a source file
Mode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/Mode.cpp.i
.PHONY : Mode.cpp.i

Mode.s: Mode.cpp.s
.PHONY : Mode.s

# target to generate assembly for a file
Mode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/Mode.cpp.s
.PHONY : Mode.cpp.s

SpeedSample.o: SpeedSample.cpp.o
.PHONY : SpeedSample.o

# target to build an object file
SpeedSample.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/SpeedSample.cpp.o
.PHONY : SpeedSample.cpp.o

SpeedSample.i: SpeedSample.cpp.i
.PHONY : SpeedSample.i

# target to preprocess a source file
SpeedSample.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/SpeedSample.cpp.i
.PHONY : SpeedSample.cpp.i

SpeedSample.s: SpeedSample.cpp.s
.PHONY : SpeedSample.s

# target to generate assembly for a file
SpeedSample.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/SpeedSample.cpp.s
.PHONY : SpeedSample.cpp.s

precomp.o: precomp.cpp.o
.PHONY : precomp.o

# target to build an object file
precomp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/precomp.cpp.o
.PHONY : precomp.cpp.o

precomp.i: precomp.cpp.i
.PHONY : precomp.i

# target to preprocess a source file
precomp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/precomp.cpp.i
.PHONY : precomp.cpp.i

precomp.s: precomp.cpp.s
.PHONY : precomp.s

# target to generate assembly for a file
precomp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/precomp.cpp.s
.PHONY : precomp.cpp.s

profanity.o: profanity.cpp.o
.PHONY : profanity.o

# target to build an object file
profanity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/profanity.cpp.o
.PHONY : profanity.cpp.o

profanity.i: profanity.cpp.i
.PHONY : profanity.i

# target to preprocess a source file
profanity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/profanity.cpp.i
.PHONY : profanity.cpp.i

profanity.s: profanity.cpp.s
.PHONY : profanity.s

# target to generate assembly for a file
profanity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TronAddressGen.dir/build.make CMakeFiles/TronAddressGen.dir/profanity.cpp.s
.PHONY : profanity.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TronAddressGen"
	@echo "... Dispatcher.o"
	@echo "... Dispatcher.i"
	@echo "... Dispatcher.s"
	@echo "... Mode.o"
	@echo "... Mode.i"
	@echo "... Mode.s"
	@echo "... SpeedSample.o"
	@echo "... SpeedSample.i"
	@echo "... SpeedSample.s"
	@echo "... precomp.o"
	@echo "... precomp.i"
	@echo "... precomp.s"
	@echo "... profanity.o"
	@echo "... profanity.i"
	@echo "... profanity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

